#!/bin/sh

wget https://gist.githubusercontent.com/pry0cc/dd2e7955d0a0222eb6c09cb283a6d614/raw/3c7bd4c20bb7649a944a36507073d9c9ab4100d8/ports.py -O ports.py

axiom-scan scope.txt -m subfinder -o subdomains.txt --threads 3

axiom-scan subdomains.txt -m dnsx -resp -o dns.txt

cat dns.txt | awk -F'[][]' '{print $2}' | anew ipaddrs.txt

sort ipaddrs.txt | uniq -d > ipaddrs.txt

axiom-scan ipaddrs.txt -m cf-check -o ipaddrs_filtered.txt

axiom-scan ipaddrs_filtered.txt -m exclude-cdn -o ipaddrs_filtered.txt

axiom-scan ipaddrs.txt -m masscan -oX masscan.xml -rate=100000

axiom-scan ipaddrs.txt -m nmap -oX nmap.xml -T4 -p- -sV

ports.py nmap.xml | anew hostnames.txt

axiom-scan hostnames.txt -m httpx -o http_hosts.txt

axiom-scan http_hosts.txt -m wpscan

axiom-scan http_hosts.txt -m gobuster-dir -o http_hosts_dirbuster.txt

axiom-scan http_hosts.txt -m gowitness -o screenshots

axiom-scan http_hosts.txt -m ffuf -o content.csv --threads 2
